### ISSUE TITLE
Search for places

### ISSUE THREAD

**Issue by brugner** [chubrik/OsmDataKit#1]
Hi. First of all, what a great project. The performance improvement from OsmSharp is huge.

I'm trying to do a sort of Google places autocomplete using a local .osm.pbf file (200mb). I want the user to type into an input and with an API return the relevant results. With OsmDataKit am able to read the file, but now how can I search for an address? I was thinking in searching through every tag that contains the search term but it seems that I can be a better option. Any help will be appreciated.

**Comment by chubrik** [comment]
Hi. And thank you for your question.

You just need to search by tags that start with `addr:`. This will give you all the address information. You can find out more at [this link](https://wiki.openstreetmap.org/wiki/Key:addr). As I understand it, different parts of the address are described in different objects. And combining information about a city, street and house into a single whole is still a non-trivial task.

**Comment by brugner** [comment]
Thank you very much! It did the trick.
