### ISSUE TITLE
Save the data back to a file

### ISSUE THREAD

**Issue by JeanCollas** [chubrik/OsmDataKit#2]
Hi !
This project looks great and like what I am looking for.
 
Would you have any advice on how to save the data gathered ?

To be more specific, I am trying to extract shapes from OSM (regions), and I am looking for a way to save it to shp files, or any sql server compatible format.

Thanks!

**Comment by chubrik** [comment]
Hi!
`OsmDataKit` can cache the gathered data to a JSON file. To do this, you need to specify the `cacheName` parameter:
```csharp
var allPlaces = OsmService.LoadCompleteObjects(
                    pbfPath: "data.osm.pbf",
                    cacheName: "cached-places",
                    filter: i => i.Tags.ContainsKey("place"));
```
After executing this code, in the `$osm-cache` folder you’ll find the file `cached-places.json`.
The structure of this JSON was originally intended for internal use. But I hope it can help you.
